from __future__ import annotations

DEFAULT_THRESHOLDS = dict(tol_dr=1e-5, tol_dv=1e-5, tol_dE=1e-4, tol_dT=1e-4, tol_dP=1e-3)
SMOKE_CI_THRESHOLDS = dict(tol_dr=1e-5, tol_dv=3e-5, tol_dE=2.5e-4, tol_dT=1e-4, tol_dP=1e-3)

PRESETS = {
    "smoke_ci": dict(
        steps=2,
        every=1,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
    ),
    "smoke_regression": dict(
        steps=80,
        every=10,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=DEFAULT_THRESHOLDS,
    ),
    "smoke": dict(
        steps=80,
        every=10,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=DEFAULT_THRESHOLDS,
    ),
    "paper": dict(
        steps=400,
        every=20,
        zones_total_list=[4, 8],
        use_verlet_list=[False, True],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False, True],
        chaos_delay_prob_list=[0.0, 0.02],
    ),
    "stress": dict(
        steps=800,
        every=20,
        zones_total_list=[8, 16],
        use_verlet_list=[True],
        verlet_k_steps_list=[10],
        chaos_mode_list=[True],
        chaos_delay_prob_list=[0.05],
    ),
    "async": dict(
        steps=300,
        every=10,
        zones_total_list=[4, 8],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
    ),
    "longrun_envelope_ci": dict(
        steps=300,
        every=10,
        zones_total_list=[4, 8],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=dict(tol_dr=100.0, tol_dv=2.0, tol_dE=500.0, tol_dT=1.0, tol_dP=1e-3),
        envelope_file="golden/longrun_envelope_v1.json",
    ),
    "sync": dict(
        steps=200,
        every=10,
        zones_total_list=[4, 8],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        sync_mode=True,
    ),
    "paper_testcases_light": dict(
        steps=120,
        every=20,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
    ),
    "interop_smoke": dict(
        steps=40,
        every=10,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=DEFAULT_THRESHOLDS,
        task_mode=True,
    ),
    "nvt_smoke": dict(
        steps=40,
        every=10,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=DEFAULT_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        task_path="examples/interop/task_nvt.yaml",
    ),
    "npt_smoke": dict(
        steps=40,
        every=10,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=DEFAULT_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        task_path="examples/interop/task_npt.yaml",
    ),
    "metal_smoke": dict(
        steps=4,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        task_path="examples/interop/task_eam_al.yaml",
    ),
    "interop_metal_smoke": dict(
        steps=4,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        task_path="examples/interop/task_eam_alloy.yaml",
    ),
    "gpu_smoke": dict(
        steps=2,
        every=1,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        sync_mode=True,
        device="cuda",
    ),
    "gpu_smoke_hw": dict(
        steps=2,
        every=1,
        zones_total_list=[4],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        sync_mode=True,
        device="cuda",
        require_effective_cuda=True,
    ),
    "gpu_interop_smoke": dict(
        steps=2,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        device="cuda",
        task_path="examples/interop/task.yaml",
    ),
    "gpu_interop_smoke_hw": dict(
        steps=2,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        device="cuda",
        require_effective_cuda=True,
        task_path="examples/interop/task.yaml",
    ),
    "gpu_metal_smoke": dict(
        steps=2,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        device="cuda",
        task_path="examples/interop/task_eam_alloy_uniform_mass.yaml",
    ),
    "gpu_metal_smoke_hw": dict(
        steps=2,
        every=1,
        zones_total_list=[1],
        use_verlet_list=[False],
        verlet_k_steps_list=[10],
        chaos_mode_list=[False],
        chaos_delay_prob_list=[0.0],
        tol=SMOKE_CI_THRESHOLDS,
        task_mode=True,
        sync_mode=True,
        device="cuda",
        require_effective_cuda=True,
        task_path="examples/interop/task_eam_alloy_uniform_mass.yaml",
    ),
    "gpu_perf_smoke": dict(
        gpu_perf_mode=True,
        device="cuda",
        require_effective_cuda=True,
        timeout=180,
        n_atoms=65536,
        delta_count=256,
        repeats=9,
        base_kernel_loop_iters=64,
        max_kernel_loop_iters=4096,
        min_kernel_ms=0.1,
        max_delta_over_full=0.65,
        max_transfer_over_kernel=4.0,
    ),
    "eam_decomp_perf_smoke": dict(
        eam_decomp_perf_mode=True,
        device="cuda",
        timeout=180,
        n_atoms=256,
        steps=1,
        repeats=1,
        warmup=0,
        zones_total=2,
        zones_nx=2,
        zones_ny=1,
        zones_nz=1,
        cutoff=6.5,
        dt=0.001,
        cell_size=2.0,
        zone_cells_w=1,
        zone_cells_s=2,
        seed=42,
    ),
    "eam_decomp_perf_gpu_heavy": dict(
        eam_decomp_perf_mode=True,
        device="cuda",
        timeout=600,
        n_atoms=10000,
        steps=768,
        repeats=1,
        warmup=1,
        zones_total=6,
        zones_nx=3,
        zones_ny=2,
        zones_nz=1,
        cutoff=6.5,
        dt=0.001,
        cell_size=2.0,
        zone_cells_w=1,
        zone_cells_s=2,
        seed=42,
        cases=["space_gpu", "time_gpu"],
        require_effective_cuda=True,
        artifact_stem="eam_decomp_perf_gpu_heavy",
    ),
    "eam_decomp_zone_sweep_gpu": dict(
        eam_decomp_zone_sweep_mode=True,
        device="cuda",
        timeout=900,
        n_atoms=10000,
        steps=256,
        repeats=1,
        warmup=1,
        seed=42,
        zone_cells_w=1,
        zone_cells_s=2,
        layouts="2:2x1x1,4:2x2x1,6:3x2x1",
        require_effective_cuda=True,
        artifact_stem="eam_decomp_zone_sweep_gpu",
    ),
    "eam_td_breakdown_gpu": dict(
        eam_td_breakdown_mode=True,
        device="cuda",
        timeout=600,
        n_atoms=10000,
        steps=768,
        repeats=1,
        warmup=1,
        seed=42,
        zones_total=2,
        zones_nx=2,
        zones_ny=1,
        zones_nz=1,
        zone_cells_w=1,
        zone_cells_s=2,
        require_effective_cuda=True,
        artifact_stem="eam_td_breakdown_gpu",
    ),
    "mpi_overlap_smoke": dict(
        mpi_overlap_mode=True,
        mpi_config="examples/td_1d_morse_static_rr_smoke4.yaml",
        mpi_ranks=[2, 4],
        overlap_list="0,1",
        strict_invariants=True,
        timeout=180,
    ),
    "mpi_overlap_cudaaware_smoke": dict(
        mpi_overlap_mode=True,
        mpi_config="examples/td_1d_morse_static_rr_smoke4.yaml",
        mpi_ranks=[2, 4],
        overlap_list="0,1",
        strict_invariants=True,
        cuda_aware=True,
        require_cuda_aware_active=True,
        timeout=180,
    ),
    "mpi_overlap_async_observe_smoke": dict(
        mpi_overlap_mode=True,
        mpi_config="examples/td_1d_morse_static_rr_smoke4.yaml",
        mpi_ranks=[2, 4],
        overlap_list="0,1",
        strict_invariants=True,
        require_async_evidence=True,
        timeout=180,
    ),
    "mpi_overlap_cudaaware_async_observe_smoke": dict(
        mpi_overlap_mode=True,
        mpi_config="examples/td_1d_morse_static_rr_smoke4.yaml",
        mpi_ranks=[2, 4],
        overlap_list="0,1",
        strict_invariants=True,
        cuda_aware=True,
        require_async_evidence=True,
        require_cuda_aware_active=True,
        timeout=180,
    ),
    "mpi_overlap_perf_observe_smoke": dict(
        mpi_overlap_mode=True,
        mpi_config="examples/td_1d_morse_static_rr_smoke4.yaml",
        mpi_ranks=[2, 4],
        overlap_list="0,1",
        strict_invariants=True,
        require_async_evidence=True,
        require_overlap_window=True,
        simulate=True,
        timeout=180,
    ),
    "cluster_scale_smoke": dict(
        cluster_scale_mode=True,
        cluster_profile="examples/cluster/cluster_profile_smoke.yaml",
        timeout=300,
    ),
    "cluster_stability_smoke": dict(
        cluster_stability_mode=True,
        cluster_profile="examples/cluster/cluster_profile_smoke.yaml",
        timeout=300,
    ),
    "mpi_transport_matrix_smoke": dict(
        mpi_transport_matrix_mode=True,
        cluster_profile="examples/cluster/cluster_profile_smoke.yaml",
        timeout=300,
    ),
    "viz_smoke": dict(
        viz_contract_mode=True,
        cluster_profile="examples/cluster/cluster_profile_smoke.yaml",
        timeout=240,
    ),
    "metal_property_smoke": dict(
        materials_property_mode=True,
        materials_fixture="examples/interop/materials_parity_suite_v2.json",
        case_prefix="eam_al_",
        timeout=300,
    ),
    "interop_metal_property_smoke": dict(
        materials_property_mode=True,
        materials_fixture="examples/interop/materials_parity_suite_v2.json",
        case_prefix="eam_alloy_",
        timeout=300,
    ),
}


def preset_names() -> tuple[str, ...]:
    return tuple(sorted(PRESETS))
