system:
  n_atoms: 240
  mass: 44.80137
  box: 80.0
  temperature: 300.0
  seed: 1

potential:
  kind: morse
  params:
    D_e: 0.29614
    a: 1.11892
    r0: 3.29692

run:
  dt: 0.05
  n_steps: 400
  thermo_every: 40
  cutoff: 8.0

td:
  cell_size: 4.0
  zones_total: 8
  zone_cells_w: 1
  zone_cells_s: 2
  traversal: snake

  fast_sync: true
  strict_fast_sync: true
  startup_mode: scatter_zones
  warmup_steps: 2
  warmup_compute: true

  buffer_k: 1.2
  use_verlet: true
  verlet_k_steps: 25
  skin_from_buffer: true

  formal_core: true
  batch_size: 4
  overlap_mode: table_support
  debug_invariants: false
  enable_step_id: true
  max_step_lag: 1
  table_max_age: 1
  max_pending_delta_atoms: 200000
  require_local_deps: true
  require_table_deps: true
  require_owner_deps: false
  require_owner_ver: true
  enable_req_holder: true
  holder_gossip: true
  chaos_mode: false
  chaos_seed: 12345
  chaos_delay_prob: 0.0

# v4.1 static_3d experimental
# deps_provider_mode: static_3d
# zones_nx: 2
# zones_ny: 2
# zones_nz: 2
# zones_total: 8
# owner_buffer: 0.0
